<template>
  <div>
    <vue-good-table
      styleClass="vgt-table striped bordered"
      max-height="1000px"
      :fixed-header="false"
      strictMode
      :columns="columns"
      :rows="rows"
      row-style-class="every-row"
      :search-options="{
        enabled: true,
        externalQuery: searchTerm,
      }"
    />
  </div>
</template>

<script>
// import the styles
import "vue-good-table/dist/vue-good-table.css";
import { VueGoodTable } from "vue-good-table";

export default {
  components: { VueGoodTable },
  name: "",
  // Always use a function for data in component else direct
  data() {
    return {
      columns: [
        {
          label: "COMPUTER",
          field: "COMPUTER",
        },
        {
          label: "C/B OUT",
          field: "C/B OUT",
        },
        {
          label: "C/B IN",
          field: "C/B IN",
        },
        {
          label: "SYS1",
          field: "SYS1",
        },
        {
          label: "SYS2",
          field: "SYS2",
        },
        {
          label: "SYS3",
          field: "SYS3",
        },
      ],
      rows: [
        {
          id: 1,
          COMPUTER: "ABCU & Y INDTR",
          "C/B OUT": "***",
          "C/B IN": "***",
          SYS1: "C10",
          SYS2: "***",
          SYS3: "***",
        },
        {
          id: 2,
          COMPUTER: "ACP",
          "C/B OUT": "10 SEC",
          "C/B IN": "1 SEC",
          SYS1: "G6",
          SYS2: "G7",
          SYS3: "M2",
        },
        {
          id: 3,
          COMPUTER: "ACCELAROMETER",
          "C/B OUT": "***",
          "C/B IN": "***",
          SYS1: "K18",
          SYS2: "***",
          SYS3: "***",
        },
        {
          id: 4,
          COMPUTER: "ADF",
          "C/B OUT": "3 SEC",
          "C/B IN": "2 SEC",
          SYS1: "H14",
          SYS2: "K2",
          SYS3: "***",
        },
        {
          id: 5,
          COMPUTER: "ADIRU",
          "C/B OUT": "15 SEC",
          "C/B IN": "5 SEC",
          SYS1: "I - 6,7(BAT)",
          SYS2: "N04,06,08",
          SYS3: "N03,05,07",
        },
        {
          id: 6,
          COMPUTER: "AEVC",
          "C/B OUT": "30 SEC",
          "C/B IN": "35 SEC",
          SYS1: "D-5,6",
          SYS2: "Y-17",
          SYS3: "***",
        },
        {
          id: 7,
          COMPUTER: "ATC",
          "C/B OUT": "03 SEC",
          "C/B IN": "3 SEC",
          SYS1: "G-11",
          SYS2: "K-7",
          SYS3: "***",
        },
        {
          id: 8,
          COMPUTER: "ATSU",
          "C/B OUT": "***",
          "C/B IN": "***",
          SYS1: "L15,16",
          SYS2: "***",
          SYS3: "***",
        },
        {
          id: 9,
          COMPUTER: "BRAKE FAN",
          "C/B OUT": "***",
          "C/B IN": "***",
          SYS1: "L32",
          SYS2: "L35",
          SYS3: "M32(CTRL)",
        },
        {
          id: 10,
          COMPUTER: "BMC",
          "C/B OUT": "1 MIN",
          "C/B IN": "22 SEC",
          SYS1: "D11, 12",
          SYS2: "Z22, 23",
          SYS3: "***",
        },
        {
          id: 11,
          COMPUTER: "BSCU",
          "C/B OUT": "1 MIN",
          "C/B IN": "1 SEC",
          SYS1: "M33, 34",
          SYS2: "M35, 36",
          SYS3: "***",
        },
        {
          id: 12,
          COMPUTER: "CARGO",
          "C/B OUT": "1 SEC",
          "C/B IN": "30 SEC",
          SYS1: "C6, T22",
          SYS2: "***",
          SYS3: "***",
        },
        {
          id: 13,
          COMPUTER: "CFDIU",
          "C/B OUT": "> 3 SEC",
          "C/B IN": "60 SEC",
          SYS1: "J17, 16",
          SYS2: "***",
          SYS3: "***",
        },
        {
          id: 14,
          COMPUTER: "CHC (cargo)",
          "C/B OUT": "2 MIN",
          "C/B IN": "26 SEC",
          SYS1: "C7, 8",
          SYS2: "***",
          SYS3: "***",
        },
        {
          id: 15,
          COMPUTER: "CIDS",
          "C/B OUT": "2 MIN",
          "C/B IN": "120 SEC",
          SYS1: "G2, 3, 4,5",
          SYS2: "M5, 6, 7,8 N11",
          SYS3: "***",
        },
        {
          id: 16,
          COMPUTER: "CPCU",
          "C/B OUT": "> 2 MIN",
          "C/B IN": "1 SEC",
          SYS1: "D9",
          SYS2: "Y22",
          SYS3: "Y23(MANUAL)",
        },
        {
          id: 17,
          COMPUTER: "CLOCK COCKPIT",
          "C/B OUT": "***",
          "C/B IN": "***",
          SYS1: "F11,N02",
          SYS2: "***",
          SYS3: "***",
        },
        {
          id: 18,
          COMPUTER: "COCKPIT SEAT",
          "C/B OUT": "***",
          "C/B IN": "***",
          SYS1: "U11",
          SYS2: "U14",
          SYS3: "***",
        },
        {
          id: 19,
          COMPUTER: "COCKPIT VIDEO",
          "C/B OUT": "***",
          "C/B IN": "***",
          SYS1: "T16",
          SYS2: "***",
          SYS3: "***",
        },
        {
          id: 20,
          COMPUTER: "DFDR",
          "C/B OUT": "***",
          "C/B IN": "***",
          SYS1: "K16",
          SYS2: "***",
          SYS3: "***",
        },
        {
          id: 21,
          COMPUTER: "DMC",
          "C/B OUT": "20 SEC",
          "C/B IN": "4 SEC",
          SYS1: "E9, E11",
          SYS2: "Q8, R8",
          SYS3: "E7, E10, Q9",
        },
        {
          id: 22,
          COMPUTER: "DMCU",
          "C/B OUT": "5 SEC",
          "C/B IN": "10 SEC",
          SYS1: "FWD GALLEY",
          SYS2: "AFT GALLEY",
          SYS3: "***",
        },
        {
          id: 23,
          COMPUTER: "DME",
          "C/B OUT": "2 SEC",
          "C/B IN": "2 SEC",
          SYS1: "G14",
          SYS2: "K6",
          SYS3: "***",
        },
        {
          id: 24,
          COMPUTER: "DMU",
          "C/B OUT": "1 SEC",
          "C/B IN": "40 SEC",
          SYS1: "K15",
          SYS2: "***",
          SYS3: "***",
        },
        {
          id: 25,
          COMPUTER: "DU",
          "C/B OUT": "2 MIN",
          "C/B IN": "***",
          SYS1: "E1,2,3,4,5",
          SYS2: "R2,3,10,11",
          SYS3: "***",
        },
        {
          id: 26,
          COMPUTER: "ECAM CNTL PANEL",
          "C/B OUT": "***",
          "C/B IN": "***",
          SYS1: "E12",
          SYS2: "***",
          SYS3: "***",
        },
        {
          id: 27,
          COMPUTER: "ECB",
          "C/B OUT": "10 SEC",
          "C/B IN": "MAX 3 SEC",
          SYS1: "L41, 42",
          SYS2: "***",
          SYS3: "***",
        },
        {
          id: 28,
          COMPUTER: "ELAC",
          "C/B OUT": "2 MIN",
          "C/B IN": "8 SEC",
          SYS1: "B11,A01(105VU)",
          SYS2: "R20,A02(105VU)",
          SYS3: "***",
        },
        {
          id: 29,
          COMPUTER: "EVMU",
          "C/B OUT": "***",
          "C/B IN": "***",
          SYS1: "R44",
          SYS2: "***",
          SYS3: "***",
        },
        {
          id: 30,
          COMPUTER: "FAC",
          "C/B OUT": "22 SEC",
          "C/B IN": "95 SEC",
          SYS1: "B3, 4",
          SYS2: "M18, 19",
          SYS3: "***",
        },
        {
          id: 31,
          COMPUTER: "FADEC",
          "C/B OUT": "2 MIN",
          "C/B IN": "2 SEC",
          SYS1: "A4, R 41",
          SYS2: "A5, Q40",
          SYS3: "***",
        },
        {
          id: 32,
          COMPUTER: "FAP",
          "C/B OUT": "***",
          "C/B IN": "***",
          SYS1: "H01 , Q14",
          SYS2: "***",
          SYS3: "***",
        },
        {
          id: 33,
          COMPUTER: "FCDC",
          "C/B OUT": "> 3 SEC",
          "C/B IN": "3 SEC",
          SYS1: "B10",
          SYS2: "Q20",
          SYS3: "***",
        },
        {
          id: 34,
          COMPUTER: "FCU",
          "C/B OUT": "7 MIN",
          "C/B IN": "10 SEC",
          SYS1: "B5",
          SYS2: "M21",
          SYS3: "***",
        },
        {
          id: 35,
          COMPUTER: "FDIU",
          "C/B OUT": "1 SEC",
          "C/B IN": "MAX 25 SEC",
          SYS1: "K17",
          SYS2: "***",
          SYS3: "***",
        },
        {
          id: 36,
          COMPUTER: "FDU",
          "C/B OUT": "30 SEC",
          "C/B IN": "57 SEC",
          SYS1: "A6, Q38",
          SYS2: "A7, Q39",
          SYS3: "L43, 44",
        },
        {
          id: 37,
          COMPUTER: "FMGC",
          "C/B OUT": "2 MIN",
          "C/B IN": "2 MIN",
          SYS1: "B2",
          SYS2: "M17",
          SYS3: "***",
        },
        {
          id: 38,
          COMPUTER: "FQIC",
          "C/B OUT": "10 SEC",
          "C/B IN": "80 SEC MAX",
          SYS1: "A-13",
          SYS2: "M-27",
          SYS3: "AUTO R27",
        },
        {
          id: 39,
          COMPUTER: "FWC",
          "C/B OUT": "30 SEC",
          "C/B IN": "50 SEC",
          SYS1: "F-1",
          SYS2: "Q-7",
          SYS3: "***",
        },
        {
          id: 40,
          COMPUTER: "GCU",
          "C/B OUT": "15 MIN",
          "C/B IN": "30 MIN",
          SYS1: "T26",
          SYS2: "T27",
          SYS3: "Y25",
        },
        {
          id: 41,
          COMPUTER: "GPCU",
          "C/B OUT": 0,
          "C/B IN": "35 MIN",
          SYS1: "Y24",
          SYS2: "***",
          SYS3: "***",
        },
        {
          id: 42,
          COMPUTER: "GPWS",
          "C/B OUT": "3 SEC",
          "C/B IN": "2 SEC",
          SYS1: "P6, 7",
          SYS2: "***",
          SYS3: "***",
        },
        {
          id: 43,
          COMPUTER: "HORN CUT OUT",
          "C/B OUT": "***",
          "C/B IN": "***",
          SYS1: "P-8,P09",
          SYS2: "***",
          SYS3: "***",
        },
        {
          id: 44,
          COMPUTER: "HF",
          "C/B OUT": "10 SEC",
          "C/B IN": "10 SEC",
          SYS1: "HA14",
          SYS2: "L13",
          SYS3: "***",
        },
        {
          id: 45,
          COMPUTER: "ILS",
          "C/B OUT": "3 SEC",
          "C/B IN": "1 SEC",
          SYS1: "G12",
          SYS2: "K9",
          SYS3: "***",
        },
        {
          id: 46,
          COMPUTER: "LGCIU",
          "C/B OUT": "30 SEC",
          "C/B IN": "1 SEC",
          SYS1: "C9 ,Q34",
          SYS2: "Q35",
          SYS3: "ESS BAT",
        },
        {
          id: 47,
          COMPUTER: "LOUDSPEAKER",
          "C/B OUT": "***",
          "C/B IN": "***",
          SYS1: "F10",
          SYS2: "P08",
          SYS3: "***",
        },
        {
          id: 48,
          COMPUTER: "MCDU",
          "C/B OUT": "10 SEC",
          "C/B IN": "45 SEC",
          SYS1: "B1",
          SYS2: "N20",
          SYS3: "***",
        },
        {
          id: 49,
          COMPUTER: "MMR",
          "C/B OUT": "***",
          "C/B IN": "***",
          SYS1: "G12",
          SYS2: "L07",
          SYS3: "***",
        },
        {
          id: 50,
          COMPUTER: "OUTER X VALVE",
          "C/B OUT": "***",
          "C/B IN": "***",
          SYS1: "L - M22 ,A10",
          SYS2: "R - M23 , A11",
          SYS3: "***",
        },
        {
          id: 51,
          COMPUTER: "PACK CONTROLLER",
          "C/B OUT": "2 MIN",
          "C/B IN": "30 SEC",
          SYS1: "X21, 22 Y18, 19",
          SYS2: "W21, 22, Y20, 21",
          SYS3: "***",
        },
        {
          id: 52,
          COMPUTER: "PHC",
          "C/B OUT": "3 SEC",
          "C/B IN": "2 SEC",
          SYS1: "D3",
          SYS2: "Y12",
          SYS3: "Y16",
        },
        {
          id: 53,
          COMPUTER: "PARKING BRAKE",
          "C/B OUT": "***",
          "C/B IN": "***",
          SYS1: "N36,37",
          SYS2: "***",
          SYS3: "***",
        },
        {
          id: 54,
          COMPUTER: "RADIO ALTIMETER",
          "C/B OUT": "3 SEC",
          "C/B IN": "3 SEC",
          SYS1: "K11",
          SYS2: "K12",
          SYS3: "***",
        },
        {
          id: 55,
          COMPUTER: "RADAR",
          "C/B OUT": "3SEC",
          "C/B IN": "15a 30SEC",
          SYS1: "K13",
          SYS2: "K14",
          SYS3: "***",
        },
        {
          id: 56,
          COMPUTER: "RMP",
          "C/B OUT": "2 SEC",
          "C/B IN": "2 SEC",
          SYS1: "G10",
          SYS2: "L2",
          SYS3: "L3",
        },
        {
          id: 57,
          COMPUTER: "SDAC",
          "C/B OUT": "2Min",
          "C/B IN": "5 SEC",
          SYS1: "F2,4,5 Q3,4",
          SYS2: "F3,5, Q2,5,6",
          SYS3: "***",
        },
        {
          id: 58,
          COMPUTER: "SDCU",
          "C/B OUT": "2Min",
          "C/B IN": "80 SEC MAX",
          SYS1: "C6",
          SYS2: "T18",
          SYS3: "***",
        },
        {
          id: 59,
          COMPUTER: "SEC",
          "C/B OUT": "5 SEC",
          "C/B IN": "18 SEC",
          SYS1: "B8 , B01(105VU)",
          SYS2: "Q18",
          SYS3: "Q19",
        },
        {
          id: 60,
          COMPUTER: "SIDE STICK LOCK",
          "C/B OUT": "***",
          "C/B IN": "***",
          SYS1: "N16",
          SYS2: "***",
          SYS3: "***",
        },
        {
          id: 61,
          COMPUTER: "SFCC",
          "C/B OUT": "2 MIN",
          "C/B IN": "< 2 SEC",
          SYS1: "B6, R21",
          SYS2: "B7, Q21",
          SYS3: "***",
        },
        {
          id: 62,
          COMPUTER: "S/BY HORIZON",
          "C/B OUT": "***",
          "C/B IN": "***",
          SYS1: "F12",
          SYS2: "***",
          SYS3: "***",
        },
        {
          id: 63,
          COMPUTER: "S/BY ALTIMETER",
          "C/B OUT": "***",
          "C/B IN": "***",
          SYS1: "F14",
          SYS2: "***",
          SYS3: "***",
        },
        {
          id: 64,
          COMPUTER: "THS ACT. MOTOR",
          "C/B OUT": "***",
          "C/B IN": "***",
          SYS1: "Q16",
          SYS2: "B9",
          SYS3: "Q17",
        },
        {
          id: 65,
          COMPUTER: "TEMP CONTROL",
          "C/B OUT": "***",
          "C/B IN": "***",
          SYS1: "D07",
          SYS2: "***",
          SYS3: "***",
        },
        {
          id: 66,
          COMPUTER: "T2CAS",
          "C/B OUT": "***",
          "C/B IN": "***",
          SYS1: "K10",
          SYS2: "***",
          SYS3: "***",
        },
        {
          id: 67,
          COMPUTER: "VHF",
          "C/B OUT": "1 SEC",
          "C/B IN": "10 SEC",
          SYS1: "G9",
          SYS2: "L4",
          SYS3: "L5",
        },
        {
          id: 68,
          COMPUTER: "VOR",
          "C/B OUT": "3 SEC",
          "C/B IN": "3 SEC",
          SYS1: "G13",
          SYS2: "K8",
          SYS3: "***",
        },
        {
          id: 69,
          COMPUTER: "WHC",
          "C/B OUT": "5 SEC",
          "C/B IN": "5 SEC",
          SYS1: "X13",
          SYS2: "W13",
          SYS3: "***",
        },
        {
          id: 70,
          COMPUTER: "LIGHT – DOME",
          "C/B OUT": "***",
          "C/B IN": "***",
          SYS1: "HO8",
          SYS2: "Y06",
          SYS3: "***",
        },
        {
          id: 71,
          COMPUTER: "NAV",
          "C/B OUT": "***",
          "C/B IN": "***",
          SYS1: "T03",
          SYS2: "T02",
          SYS3: "***",
        },
        {
          id: 72,
          COMPUTER: "LANDING",
          "C/B OUT": "***",
          "C/B IN": "***",
          SYS1: "T04 , T05 (L)",
          SYS2: "T06 , T07 (R)",
          SYS3: "***",
        },
        {
          id: 73,
          COMPUTER: "BEACON",
          "C/B OUT": "***",
          "C/B IN": "***",
          SYS1: "U06 (U)",
          SYS2: "U03 (L)",
          SYS3: "***",
        },
        {
          id: 74,
          COMPUTER: "LOGO",
          "C/B OUT": "***",
          "C/B IN": "***",
          SYS1: "V02 (L)",
          SYS2: "V03 (R)",
          SYS3: "***",
        },
        {
          id: 75,
          COMPUTER: "STROBE",
          "C/B OUT": "***",
          "C/B IN": "***",
          SYS1: "V05",
          SYS2: "***",
          SYS3: "***",
        },
        {
          id: 76,
          COMPUTER: "ENG SCAN",
          "C/B OUT": "***",
          "C/B IN": "***",
          SYS1: "W02 (L)",
          SYS2: "W03 (R)",
          SYS3: "***",
        },
        {
          id: 77,
          COMPUTER: "TURN OFF",
          "C/B OUT": "***",
          "C/B IN": "***",
          SYS1: "W06 (L)",
          SYS2: "W05 (R)",
          SYS3: "***",
        },
        {
          id: 78,
          COMPUTER: "T/O",
          "C/B OUT": "***",
          "C/B IN": "***",
          SYS1: "W07",
          SYS2: "***",
          SYS3: "***",
        },
        {
          id: 79,
          COMPUTER: "TAXI",
          "C/B OUT": "***",
          "C/B IN": "***",
          SYS1: "W08",
          SYS2: "***",
          SYS3: "***",
        },
        {
          id: 80,
          COMPUTER: "FLOOD",
          "C/B OUT": "***",
          "C/B IN": "***",
          SYS1: "Z04",
          SYS2: "Z05",
          SYS3: "Z06",
        },
        {
          id: 81,
          COMPUTER: "ENG OIL QNTY",
          "C/B OUT": "***",
          "C/B IN": "***",
          SYS1: "N39",
          SYS2: "N41",
          SYS3: "***",
        },
        {
          id: 82,
          COMPUTER: "REV LOCK",
          "C/B OUT": "***",
          "C/B IN": "***",
          SYS1: "N44",
          SYS2: "N45",
          SYS3: "***",
        },
        {
          id: 83,
          COMPUTER: "BLEED",
          "C/B OUT": "***",
          "C/B IN": "***",
          SYS1: "D11,12",
          SYS2: "Z22,23",
          SYS3: "***",
        },
        {
          id: 84,
          COMPUTER: "X BLEED VALVE",
          "C/B OUT": "***",
          "C/B IN": "***",
          SYS1: "D13",
          SYS2: "***",
          SYS3: "***",
        },
        {
          id: 85,
          COMPUTER: "FUEL - APU PUMP",
          "C/B OUT": "***",
          "C/B IN": "***",
          SYS1: "B14, K39,M38",
          SYS2: "***",
          SYS3: "***",
        },
        {
          id: 86,
          COMPUTER: "WING TANK",
          "C/B OUT": "***",
          "C/B IN": "***",
          SYS1: "N23 , N26 (L)",
          SYS2: "Q23 , Q26 (R)",
          SYS3: "P23 P26(C)",
        },
        {
          id: 87,
          COMPUTER: "FLIGHT CONTROL--",
          "C/B OUT": "***",
          "C/B IN": "***",
          SYS1: "***",
          SYS2: "***",
          SYS3: "***",
        },
        {
          id: 88,
          COMPUTER: "SLAT CNTRL",
          "C/B OUT": "***",
          "C/B IN": "***",
          SYS1: "B06",
          SYS2: "R21",
          SYS3: "***",
        },
        {
          id: 89,
          COMPUTER: "FLAP CNTRL",
          "C/B OUT": "***",
          "C/B IN": "***",
          SYS1: "B07",
          SYS2: "Q21",
          SYS3: "***",
        },
        {
          id: 90,
          COMPUTER: "SLAT/FLAP POS IND",
          "C/B OUT": "***",
          "C/B IN": "***",
          SYS1: "B12",
          SYS2: "P16",
          SYS3: "***",
        },
        {
          id: 91,
          COMPUTER: "WTB SLAT",
          "C/B OUT": "***",
          "C/B IN": "***",
          SYS1: "S06",
          SYS2: "P19",
          SYS3: "***",
        },
        {
          id: 92,
          COMPUTER: "WTB FLAP",
          "C/B OUT": "***",
          "C/B IN": "***",
          SYS1: "S07",
          SYS2: "P20",
          SYS3: "***",
        },
        {
          id: 93,
          COMPUTER: "ANTI – ICE ----",
          "C/B OUT": "***",
          "C/B IN": "***",
          SYS1: "***",
          SYS2: "***",
          SYS3: "***",
        },
        {
          id: 94,
          COMPUTER: "PITOT",
          "C/B OUT": "***",
          "C/B IN": "***",
          SYS1: "D02",
          SYS2: "Y14",
          SYS3: "Z16",
        },
        {
          id: 95,
          COMPUTER: "AOA",
          "C/B OUT": "***",
          "C/B IN": "***",
          SYS1: "D04",
          SYS2: "Y13",
          SYS3: "Z15",
        },
        {
          id: 96,
          COMPUTER: "ENG",
          "C/B OUT": "***",
          "C/B IN": "***",
          SYS1: "X10",
          SYS2: "W10",
          SYS3: "***",
        },
        {
          id: 97,
          COMPUTER: "WIPER",
          "C/B OUT": "***",
          "C/B IN": "***",
          SYS1: "X12",
          SYS2: "W12",
          SYS3: "***",
        },
        {
          id: 98,
          COMPUTER: "P2/T2",
          "C/B OUT": "***",
          "C/B IN": "***",
          SYS1: "Z10",
          SYS2: "Y10",
          SYS3: "***",
        },
        {
          id: 99,
          COMPUTER: "STATIC PROBE",
          "C/B OUT": "***",
          "C/B IN": "***",
          SYS1: "Z13",
          SYS2: "Y11",
          SYS3: "Z14",
        },
        {
          id: 100,
          COMPUTER: "TAT",
          "C/B OUT": "***",
          "C/B IN": "***",
          SYS1: "Z12",
          SYS2: "Y15",
          SYS3: "***",
        },
        {
          id: 101,
          COMPUTER: "Y PUMP",
          "C/B OUT": "***",
          "C/B IN": "***",
          SYS1: "Q36,37",
          SYS2: "***",
          SYS3: "***",
        },
        {
          id: 102,
          COMPUTER: "ELECRICAL---",
          "C/B OUT": "***",
          "C/B IN": "***",
          SYS1: "***",
          SYS2: "***",
          SYS3: "***",
        },
        {
          id: 103,
          COMPUTER: "HOT BUS",
          "C/B OUT": "***",
          "C/B IN": "***",
          SYS1: "D01,E01(105VU)",
          SYS2: "D02,E02(105VU)",
          SYS3: "***",
        },
        {
          id: 104,
          COMPUTER: "BCL",
          "C/B OUT": "***",
          "C/B IN": "***",
          SYS1: "F01,G01(1O5VU)",
          SYS2: "F02,J02(105VU)",
          SYS3: "***",
        },
        {
          id: 105,
          COMPUTER: "STATIC INVERTOR",
          "C/B OUT": "***",
          "C/B IN": "***",
          SYS1: "G02,H02(105VU)",
          SYS2: "***",
          SYS3: "***",
        },
        {
          id: 106,
          COMPUTER: "ESS TR",
          "C/B OUT": "***",
          "C/B IN": "***",
          SYS1: "C01,02(106VU)",
          SYS2: "***",
          SYS3: "***",
        },
        {
          id: 107,
          COMPUTER: "BTC",
          "C/B OUT": "***",
          "C/B IN": "***",
          SYS1: "T28,29",
          SYS2: "T30,31",
          SYS3: "***",
        },
        {
          id: 108,
          COMPUTER: "TR1",
          "C/B OUT": "***",
          "C/B IN": "***",
          SYS1: "X25,X26",
          SYS2: "***",
          SYS3: "***",
        },
      ],
    };
  },
  methods: {},
  computed: {},
};
</script>

<style scoped>
table {
  display: table;
  margin: 0;
}
tr {
  border-top: none;
}
tr:nth-child(2n) {
  background-color: transparent;
}
th,
td {
  border: none;
  padding: auto auto;
}
</style>
